### ISSUE TITLE
enlever le cadre autour du titre de la these

### ISSUE THREAD

**Issue by ouaida** [dbitouze/yathesis#2]
bonjour, 
je souhaite enlever le cadre autour du titre de la these.
Merci

**Comment by Ramdin** [comment]
Et moi, j'aimerais changer le cadre en deux lignes au-dessus et au-dessous, comme suit : 

=======================================
Magnifique thèse sur d'impressionnantes choses 
=======================================

**Comment by dbitouze** [comment]
Comme indiqué à la page 21 de la documentation, il est possible de personnaliser à peu près complètement le cadre autour du titre de la thèse. Si les styles prédéfinis (`fbox`, `shadowbox`, `ovalbox` et `none`) ne conviennent pas, il faut passer à l'option `frametitle` du code sous la forme d'une liste de clés/valeurs propres à l'environnement `tcolorbox` du package tcolorbox.

Je vous laisse le soin de chercher dans la documentation de ce package comment obtenir ce que vous souhaitez et, si vous ne trouvez pas, de demander sur un forum ou une liste d'entraide à LaTeX comment faire (de fait, cette question n'est pas propre à la classe `yathesis`).

**Comment by Ramdin** [comment]
D'accord, merci beaucoup pour votre retour rapide.
