### ISSUE TITLE
Environnement abstract presque vide

### ISSUE THREAD

**Issue by mathieu2L** [dbitouze/yathesis#29]
Lorsque l'environnement abstract est "presque" vide, cela produit une erreur (`! Paragraph ended before \isempty was complete.`).

E(C)M à partir du sample:

```
\begin{abstract}

\end{abstract}
% Production de la page de résumés :
\makeabstract
```

**Comment by dbitouze** [comment]
L'ECM suivant : 
```latex
\documentclass{yathesis}
\begin{document}
\begin{abstract}

\end{abstract}
% Production de la page de résumés :
\makeabstract
\end{document}
```
ne produisant pas cette erreur avec la version actuelle de `yathesis`, je suppose ce bug corrigé.
