### ISSUE TITLE
Style préliminaire et début de document

### ISSUE THREAD

**Issue by mathieu2L** [dbitouze/yathesis#32]
Pense-bête suite à échange (légèrement modifié) par messagerie privée.
1. au début du document, on est en style préliminaire :
   1. \frontmatter usuel (numéros de page en romain) ;
   2. titres courants avec numéros de pages ;
2. les commandes suivantes n'appliquent leurs styles respectifs (`titles` et `prepreliminary`) que localement :
   1. \maketitle ;
   2. \makekeywords, \makelaboratory, \makededication, \makeepigraph, \makeabstract.

Ainsi, dès qu'on sort de ces pages-là, les titres courants avec numéro de pages sont à nouveau affichés et l'avantage est qu'il n'y a plus besoin de déclencheur de début d'affichage des numéros de pages.

Les deux seuls inconvénients sont :
1. les chapitres ordinaires sont pourvus de titres courants même avant la page de résumés;
2. la nécessité de recourir à \mainmatter pour avoir des numéros de pages en chiffres arabes mais ça ne paraît pas trop gênant : possibilité de faire une FAQ à ce sujet.

**Comment by dbitouze** [comment]
Je suppose que les versions récentes de `yathesis` ne présentent plus ce problème.
