### ISSUE TITLE
Noms propres en mots clés, indentation en résumé  : problèmes résolus

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#35]
Comme vous le voyez en image jointe, les mots clés contiennent des noms
propres; comment pourrais-je les rendre en majuscules? Ce n'est pas prévu
peut-être?

![resume](https://cloud.githubusercontent.com/assets/1032633/5601883/e0be09e2-9323-11e4-8e08-dd24d5542120.png)

**Comment by dbitouze** [comment]
Par défaut, les mots-clés sont effectivement composés en minuscules. Pour qu'un mot ne voie pas sa casse modifiée, il suffit de le mettre en argument de la commande `\NoCaseChange`, par exemple :
```latex
\keywords{série de \NoCaseChange{Fourier}, fonction de \NoCaseChange{Wiener}}{\NoCaseChange{Fourier} series,\NoCaseChange{Wiener}'s function}
```

**Comment by Ramdin** [comment]
J'ai tout simplement dit que ça marche; en effet, pendant la compilation avec latexmk, ça s'arrête deux fois et j'ai en effet mis les lignes AVANT \begin{abstract} et après makeabstract. Mais en tapant retour chariot, ça produit un bon pdf (avec bonne indentation c-à-d), ça se compile normalement après.

Je vous envoie donc le fichier log pour que vous pourriez régler plus complètement pour le prochain mise à jour peut-être.

Pour ma part, il suffit que ça marche comme actuellement.

![sarrete](https://cloud.githubusercontent.com/assets/10378786/5602089/27b6cc28-9336-11e4-8103-eaab7e83c1db.png)


Bien cordialement,
