### ISSUE TITLE
Indentation en résumé

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#36]
L'indentation des paragraphes est différente dans le résumé. En effet, j'ai un résumé d'une page pour chaque langue (donc deux pages en totale), donc j'ai besoin d'indentations.

Merci d'avance.

![deuxproblemes](https://cloud.githubusercontent.com/assets/10378786/5602033/1a82d394-9331-11e4-9d35-1fdaff945d9c.png)

**Comment by dbitouze** [comment]
Ceci tient au fait que les résumés sont composés dans des `minipage` et `\begin{minipage}` fixe temporairement `\parindent` à `0pt`. Un moyen de s'en sortir est d'ajouter en préambule :
```latex
\makeatletter
\newlength{\YAD@ORI@parindent}
\setlength{\YAD@ORI@parindent}{\parindent}
\newcommand{\@minipagerestore}{\setlength{\parindent}{\YAD@ORI@parindent}}
\makeatother
```
ce qui modifiera tous les environnements `minipage`. Si vous ne le souhaitez pas, insérez les lignes ci-dessus plutôt juste avant `\makeabstract` et ajoutez juste après :
```latex
\makeatletter
\newcommand{\@minipagerestore}{\setlength{\parindent}{0pt}}
\makeatother
```

**Comment by Ramdin** [comment]
J'ai tout simplement dit que ça marche; en effet, pendant la compilation avec latexmk, ça s'arrête deux fois et j'ai en effet mis les lignes AVANT \begin{abstract} et après makeabstract. Mais en tapant retour chariot, ça produit un bon pdf (avec bonne indentation c-à-d), ça se compile normalement après.

Je vous envoie donc le fichier log pour que vous pourriez régler plus complètement pour le prochain mise à jour peut-être.

Pour ma part, il suffit que ça marche comme actuellement.

![sarrete](https://cloud.githubusercontent.com/assets/10378786/5602093/8e4f932a-9336-11e4-942c-bea7902edb63.png)


Bien cordialement,

**Comment by dbitouze** [comment]
Oups ! La deuxième série de lignes à ajouter est :
```latex
\makeatletter
\renewcommand{\@minipagerestore}{\setlength{\parindent}{0pt}}
\makeatother
```

**Comment by Ramdin** [comment]
Comme ça on n'a plus besoin de taper retour-chariot!

Merci.
