### ISSUE TITLE
Enlever cadre autour des figures

### ISSUE THREAD

**Issue by fmaillar** [dbitouze/yathesis#37]
Bonjour,

j'aimerais savoir comment enlever le cadre autour des figures. Bien entendu j'ai la dernière version 0.99l. Je ne sais pas si c'est important mais je tiens à souligner que je travaille sous l'environnement GNU\Linux Ubuntu 14.10 et j'ai installé TexLive 2014 à partir du DVD. 

D'avance merci pour vos réponses

**Comment by dbitouze** [comment]
Bonjour,

il suffit de commenter ou supprimer la ligne `\floatsetup[figure]{style=BOXED}` dans le fichier de configuration `thesis.cfg` situé dans le dossier `configuration`.

Merci pour cette question : il faudrait effectivement que je documente cela, au moins en FAQ.

**Comment by fmaillar** [comment]
Ça fonctionne comme je le voulais. Merci d'avoir répondu aussi rapidement.
