### ISSUE TITLE
Séparateur décimal

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#38]
Bonjour monsieur,

Voilà un autre problème. Je veux que la langue principale soit français, mais que le séparateur décimal soit un point (.) au lieu d'une virgule (,), ainsi : 0.036 au lieu de 0,036.

L'option \usepackage[locale=UK]{siunitx} ne marche pas. Si je fais, mainlanguage=english, alors les virgules sont effectivement changées en points, mais ce n'est pas une solution : je veux que la langue principale soit français... 

Pour renforcer mon point, j'utilise \num{0.00...etc} au moinst 100 fois, donc pas question de changer de package etc...

Bien cordialement,

**Comment by Ramdin** [comment]
Voilà que j'ai trouvé une solution pas tout à fait satisfaisante. 

Il suffit de mettre \num[output-decimal-marker={.}]{0.08366}  au lieu de \num{0.08366} et voilà!

Si, dans une partie, vous vouliez que le séparateur décimal soit la virgule, il suffit de ne rien mettre, ainsi :  

\num{3.1415}...

**Comment by dbitouze** [comment]
Il devrait suffire d'insérer `\sisetup{locale=UK}` dans la partie en anglais. L'exemple ci-dessous illustre cela.

```latex
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{siunitx}
\begin{document}
%
\begin{abstract}
  \num{0.08366}
\end{abstract}
\begin{abstract}
  \sisetup{locale=UK}%
  \num{0.08366}
\end{abstract}
\makeabstract
%
\chapter*{Introduction}
%
\section{En français}
\num{0.08366}
%
\section{En anglais}
\selectlanguage{english}
\sisetup{locale=UK}%
\num{0.08366}
%
\end{document}
```

**Comment by Ramdin** [comment]
Je ne l'ai pas testé ; je le ferais dans moins d'un mois et je vous dirais si cela marche ou non.

**Comment by dbitouze** [comment]
Vu le temps écoulé, je suppose que la solution proposée fonctionne.
