### ISSUE TITLE
Enlever "Titre de la thèse" et "Thesis title"

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#39]
Bonjour,

Voilà un autre issue. J'aimerais bien enlever "Titre de la thèse" et "Thesis title" en haut à gauche du titre de la thèse. Si j'enlève le cadre à l'aide de \yadsetup{frametitle=none}, le cadre et "Titre de la thèse" disparaissent. J'aimerais bien garder le cadre mais enlever la phrase "Titre de la thèse".

Merci d'avance !

**Comment by dbitouze** [comment]
C'est prévu. Cf. exemple 7.7 « Suppression d'expression définie par la classe » pages 60 et 62, ainsi que la table 7.1 page 61.
