### ISSUE TITLE
Deux page de titre françaises

### ISSUE THREAD

**Issue by fmaillar** [dbitouze/yathesis#40]
Bonjour Denis,

lorsque je mets mes titres en anglais (dans les champs optionnels du titre, sous-titres, spécialité, ...) dans le fichier characteristics.tex, ça produit deux fois la même page de titre française l'une après l'autre et ensuite celle en anglais. 

Le problème ne se produit pas lorsque je ne mets pas d'arguments anglais.

Le problème reste le même quelque soit la version final ou inprogress(*).

Comment faire pour que la page de titre française n'apparaisse qu'une seule fois ?

Merci

**Comment by dbitouze** [comment]
Le 18/03/15 à 17h47, Florian MAILLARD <notifications@github.com> a écrit :

> Bonjour Denis,

Bonjour Florian,

> lorsque je mets mes titres en anglais (dans les champs optionnels du
> titre, sous-titres, spécialité, ...) dans le fichier
> characteristics.tex, ça produit deux fois la même page de titre
> française l'une après l'autre et ensuite celle en anglais.
>
> Le problème ne se produit pas lorsque je ne mets pas d'arguments
> anglais.
>
> Le problème reste le même quelque soit la version final ou
> inprogress(*).
>
> Comment faire pour que la page de titre française n'apparaisse qu'une
> seule fois ?

Il devrait suffire de passer l'option `nofrontcover` à la commande
`\maketitle` :

```latex
\maketitle[nofrontcover]
```

Cf. documentation page 20.

> Merci

Je vous en prie.
-- 
Denis
