### ISSUE TITLE
Page dédiée au laboratoire

### ISSUE THREAD

**Issue by fmaillar** [dbitouze/yathesis#41]
Rebonjour,

Cette fois j'ai bien regardé la documentation.

Au niveau de la page consacrée au laboratoire
Comment faire pour modifier (voire même supprimer) le morceau de phrase : "Cette thèse est préparée au" ?
Parce que d'une part je ne trouve pas ça trop esthétique et d'autre part avec mon unité de recherche on dit plutôt "à" que "au".

D'avance merci.

**Comment by dbitouze** [comment]
Hum :) Cf. section « 7.4.1 (Re)Définition des expressions de la thèse » page 60 et table 7.1 page 61. Il devrait donc suffire de recourir, par exemple dans le fichier `thesis.cfg` :

- pour avoir « à » plutôt que « au », à :
```latex
\expression{prepared-at}{Cette thèse est préparée à}{This thesis has been prepared at}
```
- pour supprimer l'expression, à :
```latex
\expression{prepared-at}{}{}
```
