### ISSUE TITLE
Le nom de l'auteur n'est pas en petites majuscules

### ISSUE THREAD

**Issue by fmaillar** [dbitouze/yathesis#42]
Bonjour,

Sur la page de titre (unique en français dans mon cas) le nom de l'auteur ne s'affiche pas en petite capitales. Par contre ceux des directeurs de thèses et des membres du jury sont en petites capitales !

Cela quelque soit la version, avec ou sans l'option mainlanguage=french

J'ai bien suivi les recommandations de l'avertissement 1.3 (au niveau du petit 2) du manuel : *le nom ne doit pas être saisi en capitales (sauf pour la majuscule) car il sera __automatiquement composé en petites majuscules__.*
Dans mon cas, cet automatisme n'a pas lieu.

J'ai même essayé avec la commande \bsc, elle n'a pas eu d'effet. Comme ça fait bientôt quelques jours que je tourne autour de ce problème en fouillant la documentation, je viens vers vous pour savoir si vous avez une idée pour résoudre ce problème. 
Par avance merci.

**Comment by dbitouze** [comment]
Les petites capitales s'appliquent en général plutôt aux auteurs. Sur la ou les pages de titre d'une thèse :
- l'auteur a bien fonction d'auteur, donc son nom figure en petites capitales ;
- les directeurs de thèses et membres du jury n'ont pas fonction d'auteur donc leurs noms ne figurent pas en petites capitales.

En revanche, si certains de leurs travaux sont cités dans le corps de la thèse, ces directeurs de thèses et membres du jury ont alors fonction d'auteur, auquel cas leurs noms figurent en petites capitales dans la bibliographie (et dans le corps de la thèse, notamment si on recourt à la commande `\citeauthor`).

**Comment by dbitouze** [comment]
Oups ! Je crois que j'ai lu un peu trop vite la question, désolé :(

En fait :

1. j'ai fini par choisir de mettre les noms des directeurs de thèses et membres du jury en petites capitales y compris sur les pages de titre pour éviter les possibles confusions entre noms et prénoms ;
2. je ne vois pas ce qui, chez vous, fait que le nom de l'auteur ne figure pas en petites capitales. Pourriez-vous me fournir un [ECM](http://gte.univ-littoral.fr/members/dbitouze/pub/latex/webographie/#x1-210005.3) ?

**Comment by fmaillar** [comment]
Un ECM du preambule (avec une liste des paquets) : 

\documentclass[12pt,%
space=onehalf,% 
sepcorpaffilfrench={,\ },
sepcorpaffilenglish={,\ },
fncychap=Lenny,%Bjornstrup, 
version=final,%
fleqn,%
output=screen, % 
a4paper]{yathesis} %Ceci est la classe pour rdiger ma thèse
% Chargement manuel de packages (pas déjà chargés par la classe yathesis)
\usepackage[utf8]{inputenc}%encodage sur Linux
\usepackage[T1]{fontenc}%idem
\usepackage{lipsum} % À proscrire dans un vrai mémoire de thèse !
\usepackage{kpfonts}
\usepackage{amsmath}%pour utiliser les math
\usepackage{amsfonts}%pour caherger le mode calligraphie et le polices
\usepackage{amssymb}%pour charger les symboles mathematique
\usepackage{amsthm}%pour mettre des theoremes
\usepackage{lmodern}
\usepackage{booktabs}
\usepackage{siunitx}%pour les unites en physiques
\usepackage{pgfplots}
\usepackage{floatrow}
\usepackage{caption}
\usepackage{listings}
\usepackage{microtype}
\usepackage{varioref}
\usepackage{minitoc}
\usepackage[xindy, quiet]{imakeidx}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber,%
hyperref=false,
isbn=false,
safeinputenc,%
style=custom-numeric-comp,
natbib=true,%
maxcitenames=3,
firstinits=true,
backref=false,
sorting=none,
block=none,
autolang=other
]{biblatex}
\renewbibmacro{in:}{} %change in: par rien dans la biblio
\DeclareLanguageMapping{french}{french} %change le langage de la biblio
\DeclareFieldFormat[article]{volume}{\textbf{#1}\addcolon\space} % makes volume of journal bold and adds colon
\DeclareFieldFormat{pages}{#1} % removes pagination (p./pp.) before page numbers
\usepackage{chemist}
\usepackage{pstricks}
\usepackage{subfigure}
\usepackage{frmath}
\usepackage{tikz}
\usepackage[european]{circuitikz}
\usepackage{url}
\usepackage{epstopdf}
\usepackage{mhchem}
\usepackage{colortbl}
\usepackage[colorinlistoftodos]{todonotes}
\usepackage{stmaryrd}
\usepackage[xindy, acronyms,symbols]{glossaries}
\usepackage[colorlinks=true,%
linkcolor=black,%
urlcolor=black,%
citecolor=black]{hyperref}
\begin{document}
\setcounter{secnumdepth}{6}
\setcounter{tocdepth}{6}
\dominitoc
\dominilof
\dominilot
\faketableofcontents
\fakelistoffigures
\fakelistoftables
\maketitle[frametitle=shadowbox]
..... etc 

Et du characteristics.tex : 

\author[florian.maillard@mailoo.org]{Florian}{Maillard}
\title{Diagnostic des batteries lithium-ion par la mesure des fluctuations électriques}
\subtitle{Caractérisation du vieillissement des batteries lithium-ion par la mesure de bruits électrochimiques}
\academicfield{Sciences de l'ingénieur}
\speciality{Énergétique}
\date{12}{12}{2015}
\subject{Vieillissement des batteries lithium-ion}
\pres[url=http://www.pres-lpc.fr/, logo=images/PRES-limousin]{\acrshort{PRES} Limousin Poitou-Charentes}
\institute[url=http://www.univ-poitiers.fr/, logo=images/UP]{\acrlong{UP}}
\company[url=http://fr.dcnsgroup.com/, logo=images/DCNS]{\acrshort{DCNS}}%{DCNS \gls{DCNS}}
\doctoralschool[url=http://simmea.ed.univ-poitiers.fr/]{\acrshort{SIMMEA}}%
\laboratory[
logo=images/Pprime,%
telephone=(33)(0)5 49 49 74 16,%
fax=(33)(0)5 49 49 74 18,%
email=secretariat.direction@cnrs.pprime.fr,%
url=http://www.pprime.fr/%
]
{Institut Pprime}
{SP2MI - Téléport 2\\
11 boulevard Marie et Pierre Curie\\
BP 30179 F86962 Futuroscope Chasseneuil Cedex\\
France}
\supervisor[professor,affiliation=\acrshort{UP}]{Serguei}{Martemianov}
\cosupervisor[corps=doctor, affiliation=\acrshort{DCNS}]{Ludovic}{Madier}
\comonitor[mcf,affiliation=\acrshort{UP}]{Anthony}{Thomas}
\keywords{lithium-ion, batterie, état de charge, état de santé, bruit électrochimique}{lithium-ion, battery, state of charge, state of health, electrochemical noise}

**Comment by dbitouze** [comment]
Comme quoi, un ECM est bien pratique : le problème vient de ce que le nom de l'auteur est à la fois en gras et en petites capitales. Or, la fonte utilisée dans votre document est Latin Modern (du fait de la ligne `\usepackage{lmodern}`) et il se trouve qu'elle ne fournit pas de petites capitales grasses. Vous n'aurez pas de problème si vous utilisez une fonte fournissant cette combinaison :

- Kp-Fonts (`\usepackage{kpfonts}`) ;
- Libertine (`\usepackage{fourier}`) ;
- Fourier  (`\usepackage{fourier}`) ;
- etc.

Je vais peut-être signaler la chose dans la FAQ.

Si vous êtes attaché à la fonte Latin Modern, un moyen de s'en sortir est de faire en sorte que les noms et prénoms n'apparaissent pas en gras, au moyen de :
`\author[florian.maillard@mailoo.org]{\textmd{Florian}}{\textmd{Maillard}}`. Mais il faut alors aussi faire en sorte que les autres éléments ne soient pas non plus en gras. Je ne développerai que si vous êtes vraiment intéressé par cette solution.

Attention, vous chargiez en fait deux packages de fontes : `kpfonts` et `lmodern`, et la combinaison des deux donnait un résultat vraiment affreux :) N'en choisissez donc qu'une et, comme dit plus haut, de préférence la 1re ou une de celles signalées plus haut fournissant la combinaison petites capitales grasses.

Pour terminer, ce que vous avez fourni n'est pas un ECM :

- ça n'était pas complet : il manquait le `\end{document}` ;
- surtout, ça n'était pas minimal. Voici à quoi il aurait dû ressembler :

```latex
\documentclass{yathesis}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\begin{document}
\author{Florian}{Maillard}
\supervisor{Serguei}{Martemianov}
\maketitle
\end{document}
```

Vous auriez ainsi peut-être constaté, lors de la réduction progressive (dichotomie conseillée) de votre EC au « minimum », que le problème apparaissait ou disparaissait selon la présence ou l'absence de `\usepackage{lmodern}`.

**Comment by fmaillar** [comment]
Bonjour,

je ne m'étais jamais vraiment intéressé au fonts. Le paquet lmodern a toujours été mon choix par défaut. Merci de m'avoir éclairé sur ce point. Le paquet libertine fonctionne à merveille.
