### ISSUE TITLE
Directrice et Junior Researcher

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#43]
Bonjour, 

Voilà ce qui peut (ne pas) être ma dernière question. Ni `\supervisor[female]{...}  `ni `\supervisorfem[]{}` ne change « Directeur de thèse » en « Directrice de thèse » !

Qu'est-ce que je peux faire ?

Deuxièmement, je crois qu'il n'y a pas de traduction "officielle" du mot "chargé de recherche" en anglais, donc j'aimerais bien pouvoir utiliser "Researcher" au lieu de "Junior Researcher" ; je trouve le qualificatif "Junior" un peu superflu.

Merci d'avance.

**Comment by dbitouze** [comment]
> Voilà ce qui peut (ne pas) être ma dernière question. Ni \supervisor[female]{...} ni \supervisorfem[]{} ne change Directeur de thèse en Directrice de thèse !

J'imagine que le problème ne se pose que l'expression figurant dans la composition du jury. Alors, en effet, c'est un bug. Je ne vais pas avoir le temps de le corriger avant un certain temps mais, en attendant, vous pouvez modifier cette expression clé (comme toutes les autres d'ailleurs) en repérant son « label » à la page 61 de la documentation :
```latex
\expression{supervisors-in-committee}{Directrice de thèse}{Supervisor}
```
(à faire figurer en préambule).
>Deuxièmement, je crois qu'il n'y a pas de traduction "officielle" du mot "chargé de recherche" en anglais, donc j'aimerais bien pouvoir utiliser "Researcher" au lieu de "Junior Researcher" ; je trouve le qualificatif "Junior" un peu superflu.

(Si possible, je préférerais que vous ouvriez une « issue » par problème/question.)

Pour modifier la traduction anglaise de « chargé de recherche », vous pouvez procéder comme ci-dessus :
```latex
\expression{juniorresearcher}{charg\'e de recherche}{Researcher}%
\expression{juniorresearcherfem}{charg\'ee de recherche}{Researcher}%
```

**Comment by Ramdin** [comment]
Ça marche très bien. Merci.

**Comment by dbitouze** [comment]
Bug corrigé via ec28cb7 (version 0.99u et ultérieures)
