### ISSUE TITLE
Deux tables des matières

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#44]
Bonjour,

Il y a, par défaut apparemment, deux tables des matières : au début et à la fin. J'aimerais que les deux tables soient pareilles ou au moins interchangées (car la table des matières à la fin est plus détaillée).

Commenet faire cela ?

**Comment by dbitouze** [comment]
>Il y a, par défaut apparemment, deux tables des matières : au début et à la fin.

Non, vous pouvez mettre autant de table des matières que vous souhaitez (enfin, il en faut au moins une sans quoi la classe émet un message d'erreur), notamment une seule si vous préférez. Pour chacune d'entre elles, vous pouvez modifier le niveau de détail par défaut (sous-sections) au moyen de la clé `depth` de la commande `\tableofcontents` (cf. pages 35 et 37 de la documentation).

**Comment by Ramdin** [comment]
D'accord, mon manque d'expertise ! Je comprend maintenant. Merci beaucoup.
