### ISSUE TITLE
Table de matière pour chaque chapitre.

### ISSUE THREAD

**Issue by vietup13** [dbitouze/yathesis#45]
Bonjour M. Bitouzé,
Je veux créer des table de matière pour chaque chapitre dans la mémoire de thèse.

Tout d'abord, j'ai chargé le paquet \usepackage{minitoc} avec les commandes \dominitoc et \minitoc comme les instruction sur l'internet, mais il n'a rien affiché.

Puis, je l'ai remplacé par un autre paquet (\usepackage{etoc}). mais il y a des erreurs des incompatibilités. J'ai copié les erreurs dans les lignes suivantes.

"Package etoc Error: the command \resettocdepth is incompatible with etoc. \makedisclaimer
Package etoc Error: the command \resettocdepth is incompatible with etoc. \makekeywords
Package etoc Error: the command \resettocdepth is incompatible with etoc. \makekeywords
Package etoc Error: the command \resettocdepth is incompatible with etoc. \makelaboratory
Package etoc Error: the command \resettocdepth is incompatible with etoc. \makelaboratory
Package etoc Error: the command \resettocdepth is incompatible with etoc. \input
Package etoc Error: the command \resettocdepth is incompatible with etoc. \input
Package etoc Error: the command \resettocdepth is incompatible with etoc. \input{liminaires/dedicaces}
Package etoc Error: the command \resettocdepth is incompatible with etoc. \makeabstract
Package etoc Error: the command \resettocdepth is incompatible with etoc. \mainmatter"

Pourriez-vous m'aider de trouver la solution pour ces problèmes, s'il vous plait?

Je vous remercie d'avance.
Cordialement,
Viet

**Comment by dbitouze** [comment]
Bonjour Viet,

j'ai prévu de rendre la classe `yathesis` compatible avec le package `etoc` mais ce ne sera pas avant plusieurs mois.

En revanche, il est tout à fait possible d'utiliser le package `minitoc` avec `yathesis` comme le prouve l'ECM suivant (à compiler avec `latexmk` pour être certain que toutes les compilations nécessaires et suffisantes ont bien eu lieu) :

```latex
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{kpfonts}
\usepackage{minitoc}
\begin{document}
\dominitoc
\tableofcontents[depth=chapter,name=Sommaire]
%
\mainmatter
\chapter{Mon beau chapitre}
\minitoc
\section{Ma belle section de mon beau chapitre}
\subsection{Ma belle sous-section de ma belle section de mon beau chapitre}
\subsection{Ma belle autre sous-section de ma belle section de mon beau chapitre}
\section{Ma belle autre section de mon beau chapitre}
\subsection{Ma belle sous-section de ma belle autre section de mon beau chapitre}
\subsection{Ma belle autre sous-section de ma belle autre section de mon beau chapitre}
\chapter{Mon bel autre chapitre}
\minitoc
\section{Ma belle section de mon bel autre chapitre}
\subsection{Ma belle sous-section de ma belle section de mon bel autre chapitre}
\subsection{Ma belle autre sous-section de ma belle section de mon bel autre chapitre}
\section{Ma belle autre section de mon bel autre chapitre}
\subsection{Ma belle sous-section de ma belle autre section de mon bel autre chapitre}
\subsection{Ma belle autre sous-section de ma belle autre section de mon bel autre chapitre}
%
\tableofcontents
\end{document}
```

**Comment by dbitouze** [comment]
Possibilité de tables des matières locales automatiques (cf. options `localtocs`) ou semi-automatiques (cf. commandes `\startlocaltocs`, `\stoplocaltocs`, `\nextwithlocaltoc`, `\nextwithoutlocaltoc`) implémentée dans la version 0.99o de `yathesis`, disponible d'ici quelques jours par mise à jour de la TeX Live 2016 ou de la MiKTeX 2.9.
