### ISSUE TITLE
Épigraphes

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#46]
Bonjour monsieur,

Cette question n'est pas propre à yathesis, mais ayant chercher partout sur internet et n'ayant pas trouvé une seule bonne solution, je me permette encore une fois de vous perturber avec cette question.

J'utilise pour tout le document la fonte \usepackage[charter]{mathdesign} comme suit :+1: 
![bistreamcharter](https://cloud.githubusercontent.com/assets/10378786/8181129/a9d6a656-1423-11e5-89b3-6dbc5afee760.png)

Mais j'aimerais que les épigraphes en dessous du titre de chaque chapitre soient en une fonte différente, par exemple avec des ligatures, des longs S qui paraissent comme des f, comme dans l'image suivante :

![longs](https://cloud.githubusercontent.com/assets/10378786/8181165/0288c4f0-1424-11e5-9d30-35a40d94c4f2.png)

Qu'est-ce que je peux faire pour cela ? Par exemple, pour utiliser \usepackage[veryoldstyle]{kpfonts} justes pour les épigraphes, qu'est-ce qu'il faut faire ?

Toutes les réponses à des questions similaires que j'ai trouvées sur internet ne marchent pas.

Merci,

**Comment by dbitouze** [comment]
Je préfère de loin que toute question qui n'est pas propre à `yathesis` soit posée non pas ici mais sur une liste ou un forum dédié à LaTeX. Ce n'est pas que je refuse de vous aider personnellement, mais, là-bas, vos questions seront lues par plusieurs centaines de paires d'yeux, ce qui :

1. augmentera vos chances d'avoir une ou plusieurs réponses (éventuellement données par moi) :
     - rapides (je suis souvent débordé) ;
     - adéquates (je peux ne pas connaître de solution) ;

2. permettra aux autres de lire les réponses à vos questions, ce qui pourra toujours servir.

Par exemple, j'explique dans ma [webographie](http://gte.univ-littoral.fr/members/dbitouze/pub/latex/webographie/#x1-160005) comment procéder pour poser sur Internet des questions relatives à LaTeX.

**Comment by Ramdin** [comment]
Ok, ça marche. Je vais poser sur quelques forums.

Merci.
