### ISSUE TITLE
Deux index

### ISSUE THREAD

**Issue by Ramdin** [dbitouze/yathesis#47]
Bonjour monsieur,

J'ai essayé de créer deux index, "Index d'auteurs" et "Index de sujets" ou presque.

J'ai utilisé l'explication donnée ici : http://tex.stackexchange.com/questions/27959/how-to-create-two-separate-indices-subject-index-and-index-of-authors

Voilà, l'exemple donné dans ce lien marche bien. Mais quand j'essaie d'imiter cet exemple dans `yathesis`, cela ne marche pas. 

Avez-vous une idée pour rectifier cette erreur ? Je ne trouve pas d'explication dans la documentation.

**Comment by dbitouze** [comment]
Désolé du retard avec lequel je réponds. Pourriez-vous fournir un ECM car le suivant (disons `test.tex`) donne le résultat attendu après les compilations :

1. `pdflatex test`
1. `texindy indexA.idx`
1. `texindy indexB.idx`
1. `pdflatex test`

```latex
\documentclass{yathesis}
\usepackage[xindy]{imakeidx}
\makeindex[name=indexA,title=Index A]
\makeindex[name=indexB,title=Index B]
\begin{document}
\mainmatter
Term A\index[indexA]{Term from index A}
\par
Term B\index[indexB]{Term from index B}
\printindex[indexA]
\printindex[indexB]
\end{document}

```

**Comment by dbitouze** [comment]
Pas de retour.
