### ISSUE TITLE
Question header yathesis

### ISSUE THREAD

**Issue by Xo2021** [dbitouze/yathesis#48]
J'aimerais ajouter une partie annexe à chaque chapitre (vu que chaque chapitre de ma thèse est en fait un article publié ou soumis). Je ne veux pas quelle soit numérotée mais je souhaite que le header change car pour le moment il est toujours à "bibliographie" (j'utilise chapterbib).

J'ai essayé ceci:

\section*{Supplementary material}\label{1apdx}
\markright{Supplementary material}

mais cela ne fonctionne pas. J'aurai aussi besoin que cette section apparaisse dans la table des matières. En jouant avec secnum depth je peux tout enlever toutefois si je souhaite faire quelquechose dans ce genre ce serait pour enlever simplement les numerotation des sections mais garder les sous sections.. mais je ne suis pas sûre de vouloir faire ça...

Avez-vous une idée? Est-ce que la classe de thèse utilise fncyhdr?

Merci,

**Comment by dbitouze** [comment]
Pour résoudre tes deux problèmes à la fois, il suffit de procéder ainsi :
```latex
[...]
\chapter{A chapter}
[...]
\setsecnumdepth{none}%
\section{Supplementary material}
[...]
\resetsecnumdepth%
%
\chapter{Next chapter}
[...]
```
