### ISSUE TITLE
Glossaire, acronymes et symboles ne s'impriment plus (Résolu bizarrement)

### ISSUE THREAD

**Issue by fmaillar** [dbitouze/yathesis#49]
Bonjour Monsieur,

j'aimerais vous demander pourquoi le glossaire, les acronymes et les symboles ne s'imprime plus. Tout fonctionnait à merveille hier en compilant avec latekmk, mais aujourd'hui ils ne s'impriment plus. J'espère que vous pourrait m'aider
L'exemple minimal est:

\documentclass[11pt, space=onehalf, sepcorpaffilfrench={,\ }, sepcorpaffilenglish={,\ }, fncychap=Glenn, version=inprogress, mainlanguage=french, fleqn, nodate = true, output=screen, a4paper]{yathesis}
\geometry{inner = 0.9in, outer = 0.7in, top = 1in, bottom = 1in}
% Chargement manuel de packages (pas déjà chargés par la classe yathesis)
\usepackage[utf8]{inputenc}%encodage sur Linux
\usepackage[T1]{fontenc}%idem
\usepackage{amsmath}%pour uytiliser les math
\usepackage{amsfonts}%pour caherger le mode calligraphie et le polices
\usepackage{amssymb}%pour charger les symboles mathematique
\usepackage{amsthm}%pour mettre des theoremes
\usepackage{numprint}
\usepackage{libertine}
\usepackage{booktabs}
\usepackage{siunitx}%pour les unites en physiques
\usepackage{pgfplots}
\usepackage{floatrow}
\usepackage{caption}
\usepackage{listings}
\usepackage{microtype}
\usepackage{varioref}
\usepackage{minitoc}
\usepackage{pdfpages}
\usepackage[xindy, quiet]{imakeidx}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber, maxcitenames=15, hyperref=false, isbn=false, safeinputenc, style=custom-numeric-comp, natbib=true, firstinits=true, backref=false, sorting=none, block=none, autolang=other]{biblatex}
\renewbibmacro{in:}{} %change in: par rien dans la biblio
\DeclareLanguageMapping{french}{french} %change le langage de la biblio
\DeclareFieldFormat[article]{volume}{\textbf{#1}\addcolon\space} 
\DeclareFieldFormat{pages}{#1} % removes pagination (p./pp.) before page numbers
\usepackage{chemist}
\usepackage{pstricks}
\usepackage{subfigure}
\usepackage{frmath}
\usepackage{tikz}
\usepackage[european]{circuitikz}
\usepackage{epstopdf}
\usepackage{mhchem}
\usepackage{colortbl}
\usepackage[colorinlistoftodos]{todonotes}
\usepackage{stmaryrd}
\usepackage[xindy, acronyms,symbols]{glossaries}
\usepackage[colorlinks=true, linkcolor=black, urlcolor=black, citecolor=black]{hyperref}
\hypersetup{pdfborder={0 0 0}}
\usepackage{url}
%
% Génération de l'index :
\makeindex
%
% Spécification de la ou des ressources bibliographiques :
\addbibresource{biblioAmoi.bib}
%
% Spécification de la ou des ressources terminologiques (facultatif) :
\loadglsentries{auxiliaires/acronymes}
\loadglsentries{auxiliaires/symboles}
\loadglsentries{auxiliaires/index}
%
% Génération du glossaire :
\makeglossaries
% Importation manuelle du fichier de macros personnelles
\input{configuration/macros}
%
\begin{document}
\dominitoc
\dominilof
\dominilot
\faketableofcontents
\fakelistoffigures
\fakelistoftables
% Production des pages de couverture et de titre
\maketitle[frametitle={ovalbox}] 
% Résumés succincts :
\include{liminaires/resumes}
%
% Liste des acronymes (facultatif) :
\printacronyms
%
% Liste des symboles (facultatif) :
\printsymbols
% Table des matières
\setcounter{tocdepth}{7}
\tableofcontents
%
\mainmatter
%
\include{corps/Chap1}
%
\appendix
\include{annexes/Annexe1}
% Liste des références bibliographiques
%
\printbibliography
%
\backmatter
%
% Index (facultatif) :
\printindex
%
% Production de la 4e de couverture (facultatif) :
\makebackcover
%
\end{document}

**Comment by fmaillar** [comment]
je tiens aussi à préciser que j'avais fait une modification pour que l'index s'affiche sur 3 colonnes mais elle n'est plus appliquée. Est-ce que le bug peut venir de cette ancienne modification ?
Le code:
\makeatletter
\renewenvironment{theindex}{%
\begin{multicols}{3}[\chapter*{\indexname}][10\baselineskip]%
\addcontentsline{toc}{chapter}{\indexname}%
\setlength\parindent{0pt}\pagestyle{plain}\let\item\idxitem}
{\end{multicols}}
\makeatother

**Comment by fmaillar** [comment]
Pour faire appel dans le texte aux entrées (enregistrées dans les fichiers dédiés) je prend les commandes \acrfull, \acrshort et \acrlong .

**Comment by fmaillar** [comment]
Re bonjour,

je vous prie de m'excuser pour tout ce dérangement. Le problème est résolu mais de manière étrange. J'ai dû redémarrer complètement l'ordinateur. Je ne sais pas du tout quel mécanisme de LaTeX était en jeu.
Du coup après cette expérience, le conseil à donner si les glossaires ne s'impriment pas est de redémarrer complètement la machine.

**Comment by dbitouze** [comment]
Je ne pense pas que redémarrer la machine soit la meilleure solution.

Le mieux est probablement de compiler manuellement les glossaires, acronymes et symboles au moyen de la commande `makeglossaries these` (si le fichier maître `.tex` s'appelle `these.tex`) pour voir les éventuels messages d'erreur ; pour cela :
- **sous Linux et Mac :** utiliser un terminal ;
- **sous Windows :** utiliser l'invite de commande MSDOS ou, mieux, installer [Cygwin](https://www.cygwin.com/) pour bénéficier d'un (émulateur de) terminal *digne de ce nom*.
