### ISSUE TITLE
Protection des majuscules dans les mots-clés

### ISSUE THREAD

**Issue by egallet** [dbitouze/yathesis#50]
Bonjour,

Je voudrais savoir comment protéger les majuscules des mots-clés du manuscrit (cas des sigles ou des noms propres dans lesquels les majuscules doivent être conservées). 
Par exemple, \keywords{abc, ABC, Abc} (dans le fichier characteristics.tex) donne :
Mots clés : abc, abc, abc
alors que j'aimerais obtenir :
Mots clés : abc, ABC, Abc

Merci !

**Comment by dbitouze** [comment]
En sous-main, la classe `yathesis` utilise la commande `\MakeTextLowercase` du package `textcase` pour forcer la composition en bas de casse des mots-clés. Pour contrevenir à cela, il suffit de recourir à la commande `\NoCaseChange` fournie par ce même package :

```latex
\documentclass{yathesis}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{hyperref}
\begin{document}
\keywords{% langue principale
  abc,
  \NoCaseChange{ABC},
  \NoCaseChange{A}bc%
}{% langue secondaire
  def,
  \NoCaseChange{DEF},
  \NoCaseChange{Def}%
}
\makekeywords
\end{document}
```
