### ISSUE TITLE
Logo supplémentaire en page titre

### ISSUE THREAD

**Issue by Quentin62** [dbitouze/yathesis#52]
Bonjour,
je suis financé par 2 organismes (inria et DGA)  et j'ai donc 4 logos à mettre :
- le logo du pres (\doctoralschool)
- le logo de l'université (\institute)
- le logo d'inria (\company)
- le logo de la DGA
Pour ce dernier, je ne sais pas comment l'insérer sans en enlever un autre. Comment puis-je l'ajouter sur la même ligne que les autres ? 

Merci

**Comment by dbitouze** [comment]
Bonjour.

_A priori_, il n'y a pour l'instant pas d'autre solution que de, en amont, créer au moyen d'un logiciel de retouche d'images une image unique à partir des 2 logos.

Au passage, le logo du PRES est créé  à l'aide de la commande `\pres` et non pas `\doctoralschool`.
