### ISSUE TITLE
Problème d'impression 

### ISSUE THREAD

**Issue by Xo2021** [dbitouze/yathesis#53]
Bonjour,

J'ai demandé à l'imprimerie de mon institut de réaliser l'impression de ma thèse écrite avec la classe yathesis. Je leur avais tout d'abord transmis le fichier formaté en mode livre (défaut) mais il m'ont demandé une version page/page. Je leur ai donc renvoyé la version formaté avec l'option `oneside`. Le problème semblait être résolu (marges égales et suppressions des pages blanches de verso) mais ce n'est apparemment pas le cas dans le format du fichier pdf en lui même. Je vous copie ce que le responsable de l'impression m'a écrit:  

> il faut que le fichier soit au format A4 et page par page. La par exemple si je vais sur la page deux de votre fichier, je vois deux pages sur une feuille A3

En ouvrant le fichier avec un lecteur pdf professionnel (nitro) je me suis rendue compte que par défaut les pages (à partir de la 2e) sont effectivement affichées côte à côte. 

Serait ce possible de résoudre ce problème pour la version `oneside` au moins (et pourquoi pas pour la version livre aussi pour etre sûre d'avoir une version recto/verso correcte car je ne suis pas sûre que l'imprimerie soit en mesure de faire le format correctement)?

Merci

Xochitl Cormon

**Comment by dbitouze** [comment]
Bonjour,

je suis surpris que cette fonctionnalité pose problème : en effet, la classe charge le package `hyperref` avec l'option `pdfpagelayout=TwoColumnRight` pour que, par défaut, les afficheurs PDF qui en sont capables affichent 2 pages sur 1. Mais cela ne modifie que le mode : 

* _d'affichage_  ;
* par défaut (c.-à-d. indépendamment des réglages de l'afficheur) ;

de l'afficheur PDF ; et ce qui n'est qu'un _affichage_ peut normalement être modifié a posteriori dans les menus de l'afficheur (c'est notamment le cas avec Acrobat Reader).

Mais, au cas où le problème persiste, il suffit de passer au package `hyperref` l'option `pdfpagelayout=SinglePage` pour que l'afficheur PDF soit par défaut lancé en mode page par page. Pour ce faire, il suffit d'insérer en préambule du fichier `.tex` l'option :

    \hypersetup{pdfpagelayout=SinglePage}

**Comment by Xo2021** [comment]
Merci de la rapide réponse, je partage votre étonnement car c'est qui me
semblait aussi (que le mode d'affichage par défaut pouvait être changé),
mais apparemment l'imprimerie voyait le document comme des pages A3
paysage (probablement qu'ils utilisent un logiciel d'impression à la
noix). Bref je leur ai envoyé un nouveau pdf compilé avec l'option en
question et vous tiens au courant de la résolution du problème. 

Le 2016-09-15 17:34, Denis Bitouzé a écrit :

> Bonjour, 
> 
> je suis surpris que cette fonctionnalité pose problème : en effet, la classe charge le package hyperref avec l'option pdfpagelayout=TwoColumnRight pour que, par défaut, les afficheurs PDF qui en sont capables affichent 2 pages sur 1. Mais cela ne modifie que le mode : 
> 
> * _d'affichage_ ;
> * par défaut (c.-à-d. indépendamment des réglages de l'afficheur) ;
> 
> de l'afficheur PDF ; et ce qui n'est qu'un _affichage_ peut normalement être modifié a posteriori dans les menus de l'afficheur (c'est notamment le cas avec Acrobat Reader). 
> 
> Mais, au cas où le problème persiste, il suffit de passer au package hyperref l'option pdfpagelayout=SinglePage pour que l'afficheur PDF soit par défaut lancé en mode page par page. Pour ce faire, il suffit d'insérer en préambule du fichier .tex l'option :
> 
> \hypersetup{pdfpagelayout=SinglePage}
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

  

Links:
------
[1]
https://github.com/dbitouze/yathesis/issues/53#issuecomment-247363534
[2]
