### ISSUE TITLE
contenu de la table des matières ne s'affiche pas

### ISSUE THREAD

**Issue by emyra** [dbitouze/yathesis#55]
J'utilise la classe yathesis pour rédiger mon rapport. Je l'ai testé sur sharelatex et ca marche très bien. Mais en essayant de compiler le projet sur mon pc, le contenu de la table des matières ne s'affiche pas, ni celui de la table des figures. Sachant que je peux modifier le titre de la table. exple: \tableofcontents[name=Sommaire], mais le contenu n’apparaît pas.

**Comment by dbitouze** [comment]
Peut-être suffit-il de procéder à une seconde compilation.

**Comment by emyra** [comment]
merci pour votre réponse.
J'ai déjà essayé de compiler plusieurs fois, mais les tables de matières, des figures et des tableaux ne s'affichent pas. Seul le titre de chaque table s'affiche. (pas d'erreurs ou de warnings associés)

**Comment by dbitouze** [comment]
Il faudrait fournir un ECM pour pouvoir voir ce qui se passe. Cf. http://texnique.fr/osqa/faq/#custom-id-ecm.

**Comment by emyra** [comment]
En fait je n'ai rien changé au modèle yathesis-specimen qu'on trouve sur sharelatex. Il me semble que c'est l'exemple fournit par le package. J'essaye juste de le compiler sur mon PC.

**Comment by dbitouze** [comment]
Merci d'attacher (donc, si possible de ne pas copier-coller) le `.log`.

**Comment by emyra** [comment]
Ci-joint le contenu du log file.
[these_log_file.txt](https://github.com/dbitouze/yathesis/files/983707/these_log_file.txt)

**Comment by dbitouze** [comment]
Je n'y vois rien de problématique. Merci d'attacher le `.pdf`.

**Comment by emyra** [comment]
ci-joint le pdf. 
[these.pdf](https://github.com/dbitouze/yathesis/files/983784/these.pdf)
Sur sharelatex, ca marche très bien.

**Comment by dbitouze** [comment]
Y a-t-il des fichiers `.toc`, `.lof`, `.lot` créés (et, surtout, pas écrasés par la compilation suivante) ?

**Comment by emyra** [comment]
oui, je viens de vérifier. Il y a bien des fichiers .toc .lof et .lot mais ce sont des fichiers vides.
Que voulez vous dire par "pas écrasés par la compilation suivante" ?

**Comment by dbitouze** [comment]
>oui, je viens de vérifier. Il y a bien des fichiers .toc .lof et .lot mais ce sont des fichiers vides.

Je ne comprends vraiment pas. Pouvez-vous essayer avec le fichier :

```latex
\documentclass[french]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[a4paper]{geometry}
\usepackage{babel}
\begin{document}
\tableofcontents
\section{Test}
\end{document}
```
>Que voulez vous dire par "pas écrasés par la compilation suivante" ?

Il pourrait se faire qu'une erreur de manipulation ou une erreur de configuration de l'éditeur de texte orienté LaTeX utilisé pour compiler écrase les fichiers auxiliaires (`.log`, `.aux`, `.toc`, `.lof`, `.lot`, etc.) au début de chaque compilation.

**Comment by emyra** [comment]
J'ai testé l'exemple avec TeXworks, TeXnivCenter et TeXstudio. 
La table des matières s'affiche.

**Comment by dbitouze** [comment]
Hum, je ne vois pas du tout quel peut être le problème. Merci de refaire le test dans un répertoire vierge et, si le problème persiste, d'attacher une archive compressée de ce répertoire.

**Comment by emyra** [comment]
J'ai testé plusieurs fois mais j'ai toujours le même problème. Dommage... 
Merci beaucoup pour votre aide.

P.S J'ai essayé d'attacher une archive compressée du répertoire mais ca marche pas.
Pour info j'ai aussi essayé de télécharger yathesis.tds.zip directement http://ctan.org/pkg/yathesis,
et j'ai compilé .\doc\latex\yathesis\french\exemples\specimen\a-plat\thesis.tex
Toujours le même problème...

**Comment by dbitouze** [comment]
Vous pouvez m'envoyer le fichier compressé à denis.bitouze@univ-littoral.fr.

**Comment by dbitouze** [comment]
Ce problème, dû à un bug temporaire du package `morewrites`, [réglé](http://texnique.fr/osqa/questions/3162/yathesis-contenu-de-la-table-des-matieres-ne-saffiche-pas).
