### ISSUE TITLE
Message d'erreur : File `yathesis.cls' not found.

### ISSUE THREAD

**Issue by nelliaz** [dbitouze/yathesis#56]
Bonjour,
Bien que Texlive soit bien installé sur ma machine, je n'arrive pas à compiler sous LateXstudio, le message d'erreur étant : File `yathesis.cls' not found. \usepackage
Avez-vous une idée du problème que je rencontre ?
D'avance merci

**Comment by dbitouze** [comment]
Bonjour,

tout dépend si la TeX Live que vous avez installée est complète ou pas. Notamment, si vous êtes sous Linux et l'avez installée via les paquets de votre distribution, veillez à installer le paquet contenant `yathesis` : sous Debian et dérivées (par exemple Ubuntu) récentes, `yathesis` se trouve dans le paquet `texlive-publishers`.

**Comment by nelliaz** [comment]
Bonjour,
Merci pour votre réponse,
Je suis effectivement sous Linux Mint. L'installation que vous recommandez fait que je ne reçois plus le message d'erreur précédent mais deux nouveaux en lien avec le paquet yathesis : 
File `iftex.sty' not found. \RequirePackage{iftex}[2013/04/04]
fixltx2e is not required with releases after 2015(fixltx2e) All fixes are now in the LaTeX kernel.

J'espère ne pas abuser de votre patience,

**Comment by nelliaz** [comment]
Merci,
avec texlive-full cela marche parfaitement,
encore merci pour votre aide et votre travail

**Comment by dbitouze** [comment]
>avec texlive-full cela marche parfaitement,

Parfait.

>encore merci pour votre aide et votre travail

Je vous en prie.
