### ISSUE TITLE
Dysfonctionnement de la commande \geometry

### ISSUE THREAD

**Issue by tomjdruet** [dbitouze/yathesis#57]
La commande `\geometry` du package `geometry` ne fonctionne pas lorsque les quatre commandes facultatives `\makedisclaimer`, `\makekeywords`, `\makelaboratory` et `\makededications` ne sont pas utilisées. En revanche, dès lors que l'une d'entre elles est utilisée, le bogue dispataît.

ECM pour reproduire le bogue :
```latex
\documentclass{yathesis}
\geometry{inner=5cm,outer=5cm,top=5cm,bottom=5cm}% Par exemple
\begin{document}
\maketitle
% En ajoutant par exemple \makedisclaimer ici, le bogue disparaît.
\tableofcontents
\mainmatter
\chapter*{Introduction}
\chapter*{Conclusion}
\backmatter
\end{document}
```

**Comment by dbitouze** [comment]
En effet. En attendant que cela soit corrigé, on peut contourner ce problème en insérant la commande `\restoregeometry` après `\maketitle`.

**Comment by dbitouze** [comment]
Désolé, je testais avec une version de la classe qui corrigeait le problème et, du coup, ne le voyais pas. C'est désormais réglé (cfe3d5b41eeaf52138d9f45d092c741452f32fc6).
