### ISSUE TITLE
Dysfonctionnement de l'option localtocs si l'on cherche à numéroter jusqu'aux subsubsection

### ISSUE THREAD

**Issue by tomjdruet** [dbitouze/yathesis#58]
En utilisant l'option `localtocs/depth=subsubsection` avec `secnumdepth=subsubsection` (ou `paragraph`), les numéros se chevauchent avec le texte au niveau des tables des matières locales.

ECM pour reproduire le bogue :

```latex
\documentclass[localtocs/depth=subsubsection,secnumdepth=subsubsection]{yathesis}
\begin{document}
\maketitle
\tableofcontents
\mainmatter
\chapter{Un chapitre}
\section{Une section}
\subsection{Une sous-section}
\subsubsection{Une sous-sous-section}
\backmatter
\end{document}
```

**Comment by dbitouze** [comment]
Les tables des matières locales s'appuient sur le package `etoc`. J'ai eu de nombreux échanges avec son concepteur pour que les choses se passent au mieux avec `yathesis` mais des cas « extrêmes » comme celui-ci (profondeurs élevées des tables des matières locales *et* de la numérotation) auront probablement du mal à être pris en compte.

Je ne ferme donc pas cette issue mais il y a peu de chance qu'elle soit réglée avant un temps certain.
