### ISSUE TITLE
Problème d'entête lors de l'utilisation des commandes de sectionnement étoilées `\(sub)section*`

### ISSUE THREAD

**Issue by touhami** [dbitouze/yathesis#59]
L'utilisation des commandes de sectionnement étoilées (`\section*`, `\section*`, `\section*`, `\paragraph*`, ...) perturbe les entêtes, plus précisément supprime la numérotation dans l'entête. Il me semble que le problème est dû à la commande `\YAD@setsecnumdepth{none}` dans les définitions des commandes
`\YAD@starred@...`.

```
\documentclass{yathesis}

\usepackage{mwe}

\begin{document}
\mainmatter
\chapter{Titre du chapitre}
\section{Une section}
\subsection*{Une sous section}
\lipsum[1-20]
\section{Une autre section}
\lipsum[1-20]
\subsection*{Une sous section}
\lipsum[1-20]
\end{document}
```

**Comment by dbitouze** [comment]
Merci. Je regarde cela dès que possible.
