### ISSUE TITLE
option linktocpage de hyperref incompatible

### ISSUE THREAD

**Issue by DequekerJerome** [dbitouze/yathesis#61]
L'option `linktocpage` du package `hyperref` est devenue incompatible dans la classe `yathesis`, produisant une table des matières (toc et localtoc) erronée.
Le problème est apparu suite à la migration de la v0.99o à la v0.99p.

**Comment by dbitouze** [comment]
En effet ! Je me penche sur ce bogue aussitôt que possible.

**Comment by dbitouze** [comment]
Contournement fourni par Jean-François Burnol (auteur du package `etoc`), encore à l'étude pour s'assurer qu'il n'y a pas d'effets de bord :

```latex
\makeatletter
\let\Etoc@getnb@ORIGINAL\Etoc@getnb
\def\Etoc@getnb #1\relax\relax\etoc@{%
    \futurelet\Etoc@getnb@token
    \Etoc@getnb@ORIGINAL#1\relax\relax\etoc@}
\makeatother
```
à ajouter en préambule.

**Comment by dbitouze** [comment]
Problème réglé avec la nouvelle version de `etoc` disponible par mise à jour de la TeX Live (et, j'imagine, de la MiKTeX).
