### ISSUE TITLE
Problème date de soutenance sur yathesis

### ISSUE THREAD

**Issue by r3y3sl** [dbitouze/yathesis#62]
Bonjour Denis,

Ayant soutenu ma thèse en 2015 (et précédemment ayant suivi la formation que tu assures à P13, merci !) j'ai un problème que je n'ai pas réussi à résoudre depuis ce moment-là...

Il se trouve que la date de soutenance (qui est bien saisie sur le fichier "characteristics") n'apparaît pas dans la page de garde. A sa place on voit seulement <date de la soutenance> (avec des lettres en marron).

Je te serai reconnaissant pour tout renseignement à ce sujet et te souhaite une bonne journée

**Comment by dbitouze** [comment]
Bonjour,

les autres spécifications figurant dans le fichier `characteristics.tex` apparaissent-elles sur la page de garde ?

**Comment by r3y3sl** [comment]
Bonjour,

Merci pour ta réactivité. Les autres spécifications du fichier en question apparaissent bien sur la page de garde

**Comment by dbitouze** [comment]
Et avec quelle commande spécifies-tu la date ? En fait un [ECM](https://texnique.fr/osqa/faq/#custom-id-ecm) serait le bienvenu.

**Comment by r3y3sl** [comment]
Merci encore pour ta réponse.

Voici l'ECM du document (plus bas ce qui est inclut dans `characteristics.tex`) :

\documentclass[12pt,mainlanguage=english,space=onehalf,version=final]{yathesis}
\usepackage[DIV=14,BCOR=2mm,headinclude=true,footinclude=false]{typearea} % true
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{kpfonts}
\usepackage{booktabs}
\usepackage{siunitx}
\usepackage{pgfplots}
\usepackage{floatrow}
\usepackage{caption}
\usepackage{microtype}
\usepackage[autostyle]{csquotes}
\usepackage[backend=biber,style=authoryear-icomp,safeinputenc]{biblatex}
\usepackage{listings}
\usepackage[xindy,acronyms,symbols,toc]{glossaries}
\usepackage{eurosym}

%\input{configuration/macros}

% Macro pour mettre en forme les noms de fichiers
\newcommand\fichier[1]{\texttt{#1}}
% Macro pour mettre en forme les noms de packages LaTeX
\newcommand\package[1]{\textsf{#1}}
% Macro pour mettre en forme des locutions étrangères
\newcommand{\locution}[1]{\emph{#1}}

\begin{document}

\maketitle
\makedisclaimer
\makekeywords

\end{document}


Le contenu du fichier contenant la date de soutenance est le suivant (je mets les commentaires dans l'original, just in case) : 

% Auteur de la thèse : prénom (1er argument obligatoire), nom (2e argument obligatoire) et éventuel courriel (argument optionnel). Les éventuels accents devront figurer et le nom /ne/ doit /pas/ être saisi en capitales.
\author[machin@bidule.com]{Machin}{BIDULE}

% Titre de la thèse dans la langue principale (argument obligatoire) et dans la langue secondaire (argument optionnel).
\title[Titre de la thèse]{Thesis title}

% Sous-titre de la thèse dans la langue principale (argument obligatoire) et dans la langue secondaire (argument optionnel). À décommenter si souhaité, à commenter ou à supprimer sinon.
\subtitle[sous-titre]{subtitle}

% Champ disciplinaire dans la langue principale (argument obligatoire) et dans la langue secondaire (argument optionnel).
\academicfield[\'{E}conomie]{Economics}

% Spécialité dans la langue principale (argument obligatoire) et dans la langue secondaire (argument optionnel). À décommenter si souhaitée, à commenter ou à supprimer sinon.
\speciality[Macroéconomie]{Macroeconomics}

% Date de la soutenance, au format {jour}{mois}{année} donnés sous forme de nombres (voici ce qui n'apparaît pas... avec tous les autres fichiers cela pourrait changer (?)).
\date{13}{10}{2015}

% Sujet pour les méta-données du PDF. À décommenter si souhaité, à commenter ou à supprimer sinon.
\subject[sujet]{subject}

% Nom (argument obligatoire) du PRES. À décommenter si souhaité, à commenter ou à supprimer sinon.
\pres[logo=images/cepn,url=http://www.univ-paris13.fr/CEPN/]{Centre d'\'{E}conomie Paris Nord}

% Nom (argument obligatoire) de l'institut (principal en cas de cotutelle).
\institute[logo=images/univp13,url=http://www.univ-paris13.fr/]{Université Paris 13}

% En cas de cotutelle (normalement, seulement dans le cas de cotutelle internationale), nom (argument obligatoire) du second institut. À décommenter si souhaité, à commenter ou à supprimer sinon.
%\coinstitute[logo=images/paris13,url=http://www.univ-paris13.fr/]{Université de Paris~13}

% Nom (argument obligatoire) de l'école doctorale. À décommenter si souhaitée, à commenter ou à supprimer sinon.
\doctoralschool[url=http://www.univ-paris13.fr/ecole-doctorale-erasme/]{Erasme}

% Nom (1er argument obligatoire) et adresse (2e argument obligatoire) du laboratoire (ou de l'unité) où la thèse a été préparée, à utiliser /autant de fois que nécessaire/.
\laboratory[
logo=images/cepn,
logoheight=1.25cm,
telephone=(33)(0)1 49 40 30 00,
email=ecoledoc-erasme@univ-paris13.fr,
url=http://www.univ-paris13.fr/
]{Université Paris 13}{%
  99 Avenue Jean Baptiste Clément,	\\
  93430 Villetaneuse 				\\
  France}

% Membres du jury, saisis au moyen des commandes \supervisor, \cosupervisor, \comonitor, \referee, \committeepresident, \examiner, \guest, à utiliser /autant de fois que nécessaire/ et /seulement si nécessaire/. Toutes basées sur le même modèle, ces commandes ont 2 arguments obligatoires, successivement les prénom et nom de chaque personne. Si besoin est, on peut apporter certaines précisions en argument optionnel, au moyen des clés suivantes : - « professor », « seniorresearcher », « mcf », « mcf* », « juniorresearcher », « juniorresearcher* » (qui peuvent ne pas prendre de valeur) pour stipuler le corps auquel appartient la personne ; « affiliation » pour stipuler l'institut auquel est affiliée la personne.

\supervisor[,affiliation=Professeur \'{E}mérite Université Paris 13]{Jacques}{Mazier}
%\cosupervisor[mcf*,affiliation=ULCO]{Charles}{Baudelaire}
%\comonitor[mcf,affiliation=ULCO]{Étienne}{de la Boétie}

\referee[,affiliation=Type 1]{Prénom1}{Nom1}
\referee[,affiliation=Type 2]{Prénom2}{Nom2}
\examiner[,affiliation=Type 3]{Prénom3}{Nom3}
\examiner[,affiliation=Type 4]{Prénom4}{Nom4}
%\committeepresident[professor,affiliation=ENS Lyon]{Victor}{Hugo}
%\examiner[mcf,affiliation=Sorbonne]{Michel}{Foucault}
%\examiner[juniorresearcher,affiliation=NBA]{Reggie}{Miller}
%\examiner[juniorresearcher*,affiliation=Queens]{Freddy}{Mercury}
%\guest{Jimmy}{Hendrix}

% Mention du numéro d'ordre de la thèse (s'il est connu, ce numéro est à spécifier en argument optionnel). À décommenter si souhaité, à commenter ou à supprimer sinon.
%\ordernumber[42]

% Préparation des mots clés dans la langue principale (1er argument) et dans la langue secondaire (2e argument)
\keywords{economic policy, income distribution, capital structure, stock-flow}{politique économique, répartition du revenu, structure du capital, stock-flux}

Merci encore

**Comment by dbitouze** [comment]
Pas de retour.

**Comment by r3y3sl** [comment]
Bonjour Denis,

Désolé pour le silence. J'ai essayé de suivre tes conseils mais sans
succès. Peut-être le pb c'est moi ? ^^


Le jeu. 28 mars 2019 à 18:58, Denis Bitouzé <notifications@github.com> a
écrit :

**Comment by dbitouze** [comment]
Bonsoir r3y3sl,

pas de souci :) : c'est simplement pour faire diminuer la pile d'« issues » restantes que je clos celles qui sont encore en suspens mais dont je n'ai plus de retour.

Si le problème que tu rencontrais est encore d'actualité pour toi, je peux rouvrir cette « issue ».
