### ISSUE TITLE
Problème avec la corporation sur la page de titre

### ISSUE THREAD

**Issue by PierreMarchand20** [dbitouze/yathesis#64]
Je n'ai pas encore bien compris comment, mais il me semble que la préposition entre le role et le corps des différents membres du jury est choisi automatiquement. En tout cas, il change automatiquement quand je passe de `à l'ENS` à `au CNRS`. Par contre j'obtiens, `au Sorbonne Université`, et plus subtil, j'obtiens `à l'Inria`, ce qui est contraire à leur charte graphique (https://www.inria.fr/institut/inria-en-bref/charte-logo/charte-logo-inria/charte-identitaire voir Rappel).

Mais j'ai peut-être loupé où l'on pouvait configurer ceci.

**Comment by PierreMarchand20** [comment]
J'ai trouvé !

**Comment by dbitouze** [comment]
Je reconnais que cela est quelque peu obscur :) Mais c'est tout de même documenté section 8.1.11
« Expressions séparant corporations et affiliations des membres du jury » de la documentation de la classe et où est notamment indiqué :

>L’élision automatique des expressions contextuelles en français n’est pas robuste : elle peut en
effet ne pas donner le résultat escompté si la valeur de la clé `affiliation`, définissant
l’affiliation, a pour initiale :
— une consonne, mais est de genre féminin ;
— une voyelle, mais par le truchement d’une commande¹ , et non pas « directement ».
——————
>1. Notamment une commande d’acronyme telle que `\gls` ou `\acrshort`.

Pour les cas qui posent problème ici, il suffit de recourir par exemple à quelque chose comme :

```latex
\referee[professor,sepcorpaffilfrench=\ à la\ ,affiliation=Sorbonne Université]{René}{Descartes}
\referee[professor,sepcorpaffilfrench=,affiliation=Inria]{René}{Descartes}
```

**Comment by PierreMarchand20** [comment]
Oui merci, je n'avais pas vu cette section, désolé pour le dérangement et merci pour votre travail !

**Comment by dbitouze** [comment]
Pas de souci. Merci pour le témoignage ! :)
