### ISSUE TITLE
logoheight option only acting on 1st laboratory logo

### ISSUE THREAD

**Issue by BambOoxX** [dbitouze/yathesis#67]
The `logoheight` option only seems to have an effect on the 1st laboratory logo.

Short (non-working) example
```
\laboratory[logo=example-image-a]{laba}{}
\laboratory[logo=example-image-b,logoheight=1cm]{labb}{}
```
The 1st logo is of 1cm height but the second stays at 1.5cm

**Comment by BambOoxX** [comment]
As some logos may have very different shapes it could be nice to have an additional or replacement `logowidth` option

**Comment by dbitouze** [comment]
>The `logoheight` option only seems to have an effect on the 1st laboratory logo.

Fixed in the repository.

> As some logos may have very different shapes it could be nice to have an additional or replacement `logowidth` option

I don't see your point: changing the size of an image is always possible by just changing its height. Providing a `logowidth` option in addition to `logoheight` would be dangerous as the (okay, naive) user could change the aspect ratio of a logo.

**Comment by BambOoxX** [comment]
Yes I understand that the two options may collide. I am not using the logos on the titlepage were there height seems crucial, but on the laboratory page were their width feels more relevant to me as this page should generally be quite empty.

**Comment by dbitouze** [comment]
Since it is easy to deal with height instead of width, I won't add a `logowidth` option for the moment, but won't close this issue: if a significant number of users request this feature, I'll reconsider my decision :)

**Comment by BambOoxX** [comment]
Fine by me, thanks.
