### ISSUE TITLE
Section numbering error when referencing section from other chapter

### ISSUE THREAD

**Issue by BambOoxX** [dbitouze/yathesis#68]
When trying to modifiy the section numbering inside section names to hide the chapter number, it appeared the chapter number was also removed from references to sections coming from other chapters than the current one. 

On [stackechange ](https://tex.stackexchange.com/a/357990/141947) a hack is proposed that works for the `book` class, on which `yathesis` is based I believe. 
However, it seems there is a discrepancy in the section number here, see the example below. 
Even without the hack, the section number reads as `4` while it should be `2.101`

Do you have an idea ? 

The goal is to have the same behaviour than with the book class.

Thanks

```
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
%\renewcommand{\chaptername}{Capitolo}
%\renewcommand{\thechapter}{\Roman{chapter}}
%\renewcommand*\thesection{\arabic{section}}
%\makeatletter
%\renewcommand{\p@section}{\thechapter.}
%\makeatother
\begin{document}
See \ref{Foosection} for more information
\chapter{Other chapter}
\chapter{Foo} 
\setcounter{section}{100}
\section{Foo section} \label{Foosection}
\end{document}
```

**Comment by dbitouze** [comment]
That's clearly a bug. I'm sorry but I have no time to work on this before a few days (weeks?).

**Comment by BambOoxX** [comment]
On a complete thesis, the section numbering works fine, so I guess this is a minor bug, probably due to the minimal example, which lacks multiple components of a thesis. However, the section numbering hack does not work even in a complete thesis.

**Comment by BambOoxX** [comment]
Désolé de demander ça, mais avez-vous eu le temps de jeter un œil sur ce problème ? Je suis en train de terminer ma rédaction, et j'aimerais envoyer mon manuscrit sans ce petit souci ;). Merci !

**Comment by dbitouze** [comment]
Pouvez-vous préciser votre ECM ? Car, même si la référence « 4 » est ici pour le moins curieuse, référencer une section par son numéro (`\ref{...}`) alors que celle-ci n'est pas numérotée (elle ne se trouve pas après `\mainmatter`), c'est également assez curieux :)

Si la section référencée se trouve après `\mainmatter`, la référence est correcte, y compris dans le cas où la numérotation des sections (et chapitres) est modifiée. Ainsi l'exemple suivant donne-t-il :
>See II.101 for more information
```
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\renewcommand{\chaptername}{Capitolo}
\renewcommand{\thechapter}{\Roman{chapter}}
\renewcommand*\thesection{\arabic{section}}
\makeatletter
\renewcommand{\p@section}{\thechapter.}
\makeatother
\begin{document}
See \ref{Foosection} for more information
\mainmatter
\chapter{Other chapter}
\chapter{Foo}
\setcounter{section}{100}
\section{Foo section} \label{Foosection}
\end{document}
```

**Comment by BambOoxX** [comment]
Je vais encore passer pour un idiot. Je pensais que la commande `\p@section` corrigeait le préfixe pour les sections et sous-sections ... Mais en fait non, c'est de là que vient mon problème en réalité. 
J'ai pu corriger le problème avec votre exemple, modifié avec les quelques lignes ci-dessous.
Merci pour votre aide.

```
\makeatletter
\renewcommand{\p@section}{\thechapter.}
\renewcommand{\p@subsection}{\thechapter.}
\renewcommand{\p@subsubsection}{\thechapter.}
\makeatother
```

**Comment by dbitouze** [comment]
>Je vais encore passer pour un idiot.

Absolument pas !

>J'ai pu corriger le problème avec votre exemple

Parfait :)
