### ISSUE TITLE
[Feature request] Utilisation du paquet `tocloft`

### ISSUE THREAD

**Issue by BambOoxX** [dbitouze/yathesis#70]
Je cherche à modifier certains réglages de la liste des figures, et je n'ai pas l'impression que la classe permette cela nativement. J'ai donc utilisé le paquet `tocloft`.
 
Cependant, l'utilisation du paquet `tocloft` combiné avec le paquet `etoc` déjà chargé par la classe fait ressortir un avertissement. 

> Package etoc Warning: Please load `tocloft' /before/ `etoc'!

Cet avertissement (je ne vais pas parler d'incompatibilité puisque dans mon cas tout semble fonctionner correctement) ne peut pas être résolu en l'état. Aussi, il ne semble pas cette contrainte soit mentionnée dans la documentation actuelle de la thèse.

Ce serait peut-petre intéressent de permettre de charger ce paquet de façon optionnelle avant le paquet `etoc`, pour pouvoir paramétrer les liste en complément de ce que fait `etoc`.

**Comment by dbitouze** [comment]
>Aussi, il ne semble pas cette contrainte soit mentionnée dans la documentation actuelle de la thèse.

En effet, ça le mériterait.

>Ce serait peut-être intéressent de permettre de charger ce paquet de façon optionnelle avant le paquet `etoc`, pour pouvoir paramétrer les liste en complément de ce que fait `etoc`.

Le problème est qu'il est fort possible qu'il y ait d'autres packages qui nécessitent ce genre de choses et ça alourdirait l'usage de `yathesis` ; mais je vais y réfléchir. En attendant, une solution (non testée) consiste à faire figurer dans le fichier (maître) `.tex`, avant `\documentclass`, la commande :

`\RequirePackage{tocloft}`

**Comment by BambOoxX** [comment]
Oui je pense que vous proposez fonctionne dans ce cas, et cette problématique est valable pour toute classe. 

Le problème est que quelqu'un pourrait se retrouver dans une situation où il faut charger un paquet entre deux autres paquets déjà chargés par la classe, ce qui est certes peu probable, mais pas impossible.

J'ai un peu cherché et un paquet `afterpackage` permet d'exécuter du code après le chargement d'un paquet spécifique. Ce serait peut-être pratique pour ce genre de situation.

**Comment by dbitouze** [comment]
>Le problème est que quelqu'un pourrait se retrouver dans une situation où il faut charger un paquet entre deux autres paquets déjà chargés par la classe, ce qui est certes peu probable, mais pas impossible.

En effet, et ce problème est inhérent à toutes les classes qui chargent des packages en sous-main.

>J'ai un peu cherché et un paquet `afterpackage` permet d'exécuter du code après le chargement d'un paquet spécifique. Cela peut peut-être servir de base pour une amélioration de la classe de ce point de vue.

Il faudrait alors plutôt un package `betweenpackages` :) Ce qui est dommage, c'est que le package [`pkgloader`](https://www.ctan.org/pkg/pkgloader) serait d'un grand secours, mais il est [actuellement bogué et ne semble pas prêt d'être corrigé](https://github.com/mhelvens/latex-pkgloader/issues/12).

**Comment by BambOoxX** [comment]
> En effet, et ce problème est inhérent à toutes les classes qui chargent des packages en sous-main.

Oui, j'ai failli le mettre dans mon commentaire précédent ;), c'est juste que je n'utilise pas souvent de classes de ce type.

`pkgloader` serait en effet très intéressant, mais je suis d'accord, il ne semble pas être en développement soutenu.

**Comment by BambOoxX** [comment]
Une remarque concernant le chargement du paquet `tocloft` avant `etoc`, dans mon cas, latex renvoie une erreur 
>! Undefined control sequence.
><argument> \if@cftnctoc
>                       \else \renewcommand *\etocstandarddisplaystyle {\eto...

**Comment by dbitouze** [comment]
Ce problème n'est pas lié à `yathesis` ni à `etoc` puisque le même genre de message est émis avec :
```
\RequirePackage{tocloft}
\documentclass{article}
\renewcommand{\cftdot}{\ensuremath{\ast}}
\begin{document}
Foo.
\end{document}
```
et la raison en est donnée [ici](https://tex.stackexchange.com/a/511303/18401).

**Comment by BambOoxX** [comment]
C'est agréable quand une communauté d'utilisateurs est aussi réactive...
