### ISSUE TITLE
Apparition de "french" dans le document

### ISSUE THREAD

**Issue by BambOoxX** [dbitouze/yathesis#71]
Je viens de recompiler un document et j'ai vu que des `french` sont apparus à certains endroits dans celui-ci. 
J'ai pu reproduire le problème avec l'exemple minimal ci-dessous.
```
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\begin{document}
\mainmatter
\chapter{Foo}
\section{Foo section}
\end{document}
```
qui donne
![image](https://user-images.githubusercontent.com/42067365/66640151-ab5ed580-ec18-11e9-888c-73238d55fa12.png)
Le même exemple avec la classe `book` donne
![image](https://user-images.githubusercontent.com/42067365/66640249-e52fdc00-ec18-11e9-8841-9f0f087dcd31.png)

Ma distribution est à jour, je suppose donc que c'est une mise à jour récente d'un des paquets chargés par `yathesis` qui doit faire ça, mais je ne vois pas comment isoler le problème plus précisément. 
Un idée sur ce qui pourrait causer ce problème ?

**Comment by BambOoxX** [comment]
J'ai essayé en chargeant les paquet listés dans la documentation à l'annexe F. Mais le problème n'apparaît toujours pas avec la classe `book`

```
\documentclass{book}
\usepackage{pgfopts}
\usepackage{etoolbox}
\usepackage{xpatch}
\usepackage{morewrites}
\usepackage{filehook}
\usepackage{xifthen}
\usepackage{xkeyval}
\usepackage{geometry}
\usepackage{graphicx}
\usepackage{environ}
\usepackage{adjustbox}
\usepackage{array}
\usepackage{xstring}
\usepackage{textcase}
\usepackage{iftex}
\usepackage{epigraph}
\usepackage{tcolorbox}
\usepackage{marvosym}
\usepackage{setspace}
\usepackage{tocbibind}
\usepackage{nonumonpart}
\usepackage{fncychap}
\usepackage{titleps}
\usepackage{xcolor}
\usepackage{datatool}
\usepackage{ifdraft}
\usepackage{draftwatermark}
\usepackage{babel}
\usepackage{etoc}
\usepackage{iflang}
\usepackage{translator}
\usepackage{datetime}
\usepackage{hyperref}
\usepackage{hypcap}
\usepackage{bookmark}

\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\begin{document}
\mainmatter
\chapter{Foo}
\section{Foo section}
\end{document}
```

**Comment by dbitouze** [comment]
Argh ! Désolé pour tous ces désagréments avec la classe `yathesis`.

Je vais essayer cet après-midi de trouver d'où vient ce problème (qui semble se manifester à chaque fois qu'un chapitre ou une section est inséré).

**Comment by BambOoxX** [comment]
Pas de souci, c'est vraiment très surprenant, je n'ai jusqu'hier pas eu ce problème, qui s'est soudainement manifesté !

**Comment by dbitouze** [comment]
Pouvez-vous me dire quels packages ont été mis à jour lors de votre mise à jour de la TeX Live hier ? Si vous êtes sous Linux,  vous pouvez les repérer au moyen  d'une commande analogue à :

`tail -n100 /usr/local/texlive/2019/texmf-var/web2c/tlmgr.log`

**Comment by BambOoxX** [comment]
Je ne suis pas sous TeXLive mais les paquets mis à jour hier étaient
````
amsmath
graphics
hyperref
ltxbase
miktex-misc
miktex-synctex-bin
tools
````

**Comment by dbitouze** [comment]
C'est le package `titlesec` qui est à l'origine de l'erreur, comme signalé [ici](https://github.com/jbezos/titlesec/issues/23) et [là](https://tex.stackexchange.com/q/511782/18401). Grâce aux dons extra-voyants d'Ulrike Fischer, une solution en attendant un correctif de `titlesec` est comme suit :

```latex
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
% Début correctif
\makeatletter
\def\ttl@mb@mark{\csname markboth \endcsname} % patch
\makeatother
% Fin correctif
\begin{document}
\mainmatter
\chapter{Foo}
\section{Foo section}
Coucou
\end{document}
```

**Comment by BambOoxX** [comment]
C'est très bien ! Cette solution fonctionne aussi sur un exemple complet.

**Comment by dbitouze** [comment]
Suite à la mise à jour du package `titlesec`, le problème ne se pose plus.
