### ISSUE TITLE
Alinéa manquant pour premier paragraphe d'une section avec mainlanguage=english

### ISSUE THREAD

**Issue by anthony14610** [dbitouze/yathesis#72]
J'écris un document avec la classe yathesis et l'option mainlanguage=english. Le problème c'est qu'avec cette option je perds l'alinéa du premier paragraphe d'une nouvelle section (pareil pour chapter, subsection, subsubsection,...). [alinea-manquant.pdf](https://github.com/dbitouze/yathesis/files/4219766/alinea-manquant.pdf)
Est-il possible de récupérer cet alinéa comme pour l'option mainlanguage=french  ?

**Comment by dbitouze** [comment]
Cette mise en page n'est pas propre à la classe `yathesis`, mais à la typographie anglaise (américaine ?) :

```latex
\documentclass[french,english]{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage{lipsum}
\usepackage[a4paper]{geometry}
\usepackage{babel}
\begin{document}
\section{Test}
\lipsum[1]

\selectlanguage{french}

\section{Test}
\lipsum[1]
\end{document}
```
![test](https://user-images.githubusercontent.com/1032633/74746921-6dc52580-5266-11ea-937e-8773e6612d4b.png)

On peut s'en sortir en chargeant le package `indentfirst`.
