### ISSUE TITLE
Caractéristiques dans le préambule

### ISSUE THREAD

**Issue by jsalort** [dbitouze/yathesis#76]
L'exemple complet minimal suivant ne compile pas:
```latex
\documentclass[hdr]{yathesis}
\author{Toto}{Titi}
\begin{document}
\maketitle
\end{document} 
```
Si on déplace `\author` dans le corps, ça fonctionne.
Donc, il y a une erreur dans le documentation (§2.1 page 5) qui stipule que l'on peut placer les caractéristiques dans le corps ou dans le préambule.

**Comment by dbitouze** [comment]
La nouvelle version (1.0.4) de la classe règle ce problème. Elle est disponible par mise à jour des distributions TeX Live ou MiKTeX.
