### ISSUE TITLE
École doctorale facultative pour les manuscrits de HDR

### ISSUE THREAD

**Issue by jsalort** [dbitouze/yathesis#77]
Par défaut, "École doctorale" est toujours considérée comme obligatoire.
Or, beaucoup de manuscrits de HDR ne la mentionnent pas.
Remarque de Jean-Yves Baudais: le texte de loi relatif à l'HDR ne la mentionne pas:
https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=LEGITEXT000028933129&dateTexte=20200904

**Comment by dbitouze** [comment]
La nouvelle version (1.0.4) de la classe règle ce problème. Elle est disponible par mise à jour des distributions TeX Live ou MiKTeX.

**Comment by jsalort** [comment]
Super, je vais essayer. Merci !
