### ISSUE TITLE
Féminisation des membres du jury sur la page de titre

### ISSUE THREAD

**Issue by alasic** [dbitouze/yathesis#78]
Avec la dernière version de TexLive2020 et de ses packages, les membres du jury deviennent tous féminins : le directeur devient une « directrice », les rapporteurs deviennent des « rapporteures », etc.

En bref, les spécifications de genre (male, female) sont totalement ignorés.

Le problème ne se posait pas avec une installation TexLive moins récente.

**Comment by dbitouze** [comment]
En effet :frowning_face:  Je pense le problème dû à une mise à jour majeure du noyau LaTeX (intervenue il y a quelques jours). Je traque le bogue dès que possible.

**Comment by dbitouze** [comment]
@alasic Le problème est en fait dû à un changement dans le package `pgfkeys` (dont la classe `yathesis` fait usage) intervenu lors de la sortie (le 28/09/2020) de la version `3.16` du package `pgf`.

En attendant une nouvelle version de `pgf` qui [règlera le problème](https://github.com/pgf-tikz/pgf/commit/bf46600f8ed45034fca7f4343c71330d99898acd), il suffit de placer le fichier [`pgfkeys.code.tex` corrigé](https://raw.githubusercontent.com/pgf-tikz/pgf/master/tex/generic/pgf/utilities/pgfkeys.code.tex) dans le même dossier que les fichiers LaTeX dont la classe de document est `yathesis`.

**Comment by alasic** [comment]
Très bien, merci !!

**Comment by dbitouze** [comment]
La nouvelle version (1.0.4) de la classe règle ce problème. Elle est disponible par mise à jour des distributions TeX Live ou MiKTeX.
