### ISSUE TITLE
Liens frama.link morts dans la bibliographie

### ISSUE THREAD

**Issue by OlivierNicole** [dbitouze/yathesis#84]
Bonjour et merci pour votre travail sur yathesis,

Dans la bibliographie, les liens vers deux conférences de l'auteur sont des liens vers le raccourcisseur d'URL https://frama.link/, un service qui a été démantelé par Framasoft.

**Comment by dbitouze** [comment]
Merci pour le témoignage et pour m'avoir signalé ce problème. Je ne suis pas certain d'avoir le temps de le régler dans l'immédiat, aussi vais-je pour l'instant ne pas clore cette issue.
