### ISSUE TITLE
Position des pages paires/impaires inversée

### ISSUE THREAD

**Issue by msavaryleblanc** [dbitouze/yathesis#88]
Bonjour,

tout d'abord merci pour cette classe très pratique !
J'utilise la classe yathesis depuis le template overleaf que j'ai importé directement depuis le site.
Je rencontre un problème avec l'alignement des pages en mode livre.
Les chapitres et autres sections commencent bien sur une page impaire, mais leur alignement se fait à gauche (pour une page de gauche du livre, comme sur le screenshot joint).

Comment faire pour que les chapitres et autres sections démarrent sur des pages de droite du livre, dans le sens naturel de lecture ? C'est à dire pour que la marge plus grande soit située à gauche sur toutes ces pages ?

![image](https://user-images.githubusercontent.com/31726477/136960018-4189aa3c-96fe-4b7c-b975-bdf120160030.png)
![image](https://user-images.githubusercontent.com/31726477/136960298-c04cfa30-03f1-407a-b013-06518b1e53e5.png)

D'avance merci,
Maxime

**Comment by dbitouze** [comment]
Je vous en prie. J'espère que ce format comporte des dimensions car, là, c'est un peu vague :) En tout cas, il vous suffit d'utiliser, via sa commande `\geometry`, les options du package `geometry`, par exemple ainsi :
```latex
\geometry{hdivide={4cm,14.75cm,}}
```
où les dimensions sont les largeurs : la 1re de la marge de gauche, la 2e de la zone de texte et la 3e de la marge de droite ; et si cette dernière n'est pas précisée, elle est automatiquement calculée en fonction de la largeur du papier. 

Cependant, puisque le problème est essentiellement dû au fait qu'il faille prendre en compte la reliure, je vous conseille de plutôt définir les marges intérieure (`inner`) et extérieure (`outer`) sans en tenir compte, et de spécifier celle de la reliure au moyen de l'option `bindingoffset` par exemple ainsi :
```latex
\geometry{inner=2cm,outer=2cm,bindingoffset=1cm}
```

ECM :
```latex
\documentclass{yathesis}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lipsum} % À proscrire dans un vrai mémoire de thèse !
\usepackage{kpfonts}
\geometry{%
  % showframe,
  inner=2cm,
  outer=2cm,
  bindingoffset=1cm
}
\begin{document}
\lipsum[1-25]
\end{document}
```
