### ISSUE TITLE
Message d'erreur package glossaries

### ISSUE THREAD

**Issue by guillaume-hps** [dbitouze/yathesis#95]
Bonjour,
J'utilise actuellement le package yathesis pour rédiger (merci encore pour ce formidable outil 🥇 ) mais voilà j'ai tjs le message d'erreur suivant :
Fichier : yathesis.cls Type : avertissement Message :Generic hook 'package/after/glossaries' is deprecated.

Je ne pense pas que ce message soit 'fatal' mais tout de même j'aimerais comprendre... 
À votre dispo pour plus d'informations,

**Comment by u-fischer** [comment]
That is due to an error in hopatch which I will correct. But generally I don't see a point to use hopatch anymore, the command doesn't do more than the generic LaTeX hooks (actually hopatch uses them too ...).

**Comment by dbitouze** [comment]
Merci pour le témoignage !
